# HYPRLOCK CONFIG

# GENERAL
general {
    disable_loading_bar = true
    grace = 2
    hide_cursor = true
    no_fade_in = false
}

# BACKGROUND
background {
    monitor =
    path = /home/som/pictures/wallpapers/wesley-pribadi-iS1NV9yN0Lg-unsplash.jpg
    blur_passes = 0
    blur_size = 0
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(200, 200, 200, 1.0)
    font_size = 55
    font_family = Fira Code Nerd Font
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# DATE
label {
    monitor =
    text = cmd[update:18000000] echo "$(date +'%A, %-d %B %Y')"
    color = rgba(200, 200, 200, 1.0)
    font_size = 24
    font_family = Fira Code Nerd Font
    position = -100, -150
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 50
    position = 0, -80
    halign = center
    valign = center
    rounding = -1
    border_size = 2
    border_color = rgb(17, 17, 17)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, -20
    halign = center
    valign = center
}

# Music label removed (didn't work properly)
